### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by chmielowiec** [amelchio/pysonos#57]
Hello

On current HA dev (v110) I get following exception with my symfonisk speaker and spotify account.

```
Exception happened during processing of request from ('192.168.1.142', 39703)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/events.py", line 100, in __init__
    super(EventNotifyHandler, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/events.py", line 109, in do_NOTIFY
    self.handle_notification(headers, content)
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/events_base.py", line 239, in handle_notification
    variables = parse_event_xml(content)
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/events_base.py", line 107, in parse_event_xml
    didl = from_didl_string(value)
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/data_structures_entry.py", line 55, in from_didl_string
    item = attempt_datastructure_upgrade(item)
  File "/Users/robert/Workspaces/home-assistant/venv/lib/python3.7/site-packages/pysonos/data_structures_entry.py", line 89, in attempt_datastructure_upgrade
    if resource.uri.startswith('x-sonos-http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

`resource` variable contain result of `pysonos.data_structure_quirks.apply_resource_quirks` function with `protocol_info == 'DUMMY_ADDED_BY_QUIRK'`

**Comment by amelchio** [comment]
Thank you, should be fixed by home-assistant/core#35617.
